services:
  - type: web
    name: portfolio
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn portfolio_site.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: your-very-secret-key
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
