# Generated by Django 5.2.1 on 2025-06-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Me', max_length=200)),
                ('description', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('degree_type', models.CharField(choices=[('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('bootcamp', 'Bootcamp'), ('other', 'Other')], default='bachelor', max_length=20)),
                ('field_of_study', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('gpa', models.CharField(blank=True, help_text='GPA or Grade', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('institution_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Order for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming Languages'), ('frontend', 'Frontend Technologies'), ('backend', 'Backend Technologies'), ('database', 'Database'), ('devops', 'DevOps & Tools'), ('other', 'Other')], default='other', max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('percentage', models.IntegerField(default=75, help_text='Skill level percentage (0-100)')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Order for display')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(help_text='Brief description for project cards', max_length=300)),
                ('project_type', models.CharField(choices=[('web', 'Web Application'), ('mobile', 'Mobile Application'), ('desktop', 'Desktop Application'), ('api', 'API/Backend'), ('data', 'Data Science/ML'), ('other', 'Other')], default='web', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('live_url', models.URLField(blank=True, help_text='Live project URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL')),
                ('demo_url', models.URLField(blank=True, help_text='Demo/video URL')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Order for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.skill')),
            ],
            options={
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('experience_type', models.CharField(choices=[('work', 'Work Experience'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('volunteer', 'Volunteer')], default='work', max_length=20)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if current position', null=True)),
                ('company_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Order for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technologies_used', models.ManyToManyField(blank=True, related_name='experiences', to='portfolio.skill')),
            ],
            options={
                'ordering': ['-start_date', 'order'],
            },
        ),
    ]
